CS2103-AY1819S1-F10-2/main

docs/DeveloperGuide.adoc

Corrected mistakes and made instructions more clear in section 1.2 "Setting up the project in your computer" of the Dev Guide.

Update Dev Guide section 1.2 (Setting up in com)

---

src/main/java/seedu/address/storage/XmlAdaptedLoan.java
src/main/java/seedu/address/ui/LoanListPanel.java
src/test/java/seedu/address/model/loan/UniqueLoanListTest.java
src/test/java/seedu/address/storage/XmlAdaptedLoanTest.java
src/test/java/seedu/address/ui/LoanCardTest.java

Fixed specified Codacy errors as instructed in https://github.com/CS2103-AY1819S1-F10-2/main/pull/10#issuecomment-427546357

Codacy check

---

docs/DeveloperGuide.adoc

Fixes issue https://github.com/CS2103-AY1819S1-F10-2/main/issues/42

Add use cases in dev guide

---

docs/DeveloperGuide.adoc

Added user stories in the Developer Guide..

Added user stories in Dev Guide

---

src/main/java/seedu/address/model/bike/Bike.java
src/main/java/seedu/address/model/bike/BikeStatus.java
src/test/java/seedu/address/model/bike/BikeTest.java
src/test/java/seedu/address/testutil/BikeBuilder.java

https://github.com/CS2103-AY1819S1-F10-2/main/issues/70
It is still an orphaned class for now; no classes or commands are associated with it.

Add Bike class

---

src/main/java/seedu/address/model/loan/Nric.java
src/test/java/seedu/address/model/loan/NricTest.java

Add nric class

---

src/test/data/XmlSerializableLoanBookTest/typicalLoanBook.xml
src/test/data/XmlSerializableLoanBookTest/typicalLoansLoanBook.xml
src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
src/test/java/seedu/address/logic/commands/ClearCommandTest.java
src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
src/test/java/seedu/address/logic/commands/EditCommandTest.java
src/test/java/seedu/address/logic/commands/FindCommandTest.java
src/test/java/seedu/address/logic/commands/ListCommandTest.java
src/test/java/seedu/address/logic/commands/RedoCommandTest.java
src/test/java/seedu/address/logic/commands/SelectCommandTest.java
src/test/java/seedu/address/logic/commands/UndoCommandTest.java
src/test/java/seedu/address/model/LoanBookTest.java
src/test/java/seedu/address/storage/StorageManagerTest.java
src/test/java/seedu/address/storage/XmlLoanBookStorageTest.java
src/test/java/seedu/address/storage/XmlSerializableLoanBookTest.java
src/test/java/seedu/address/testutil/TypicalBikes.java
src/test/java/seedu/address/testutil/TypicalLoanBook.java
src/test/java/seedu/address/testutil/TypicalLoans.java
src/test/java/systemtests/LoanBookSystemTest.java

Extracted `getTypicalLoanBook()` from `TypicalLoans` into its own file, and added Bikes into it.

Extract TypicalLoanBook and add Bike support

---

docs/DeveloperGuide.adoc
docs/UserGuide.adoc

Added more content for guides in terms of summary command.
Fixed some minor English and augmented some details in the guides.
Partially Fix #117 as all index were changed to LOAN_ID

Update dev and user guides 

---

src/main/java/loanbook/logic/parser/ParserUtil.java

Fix https://github.com/CS2103-AY1819S1-F10-2/main/issues/128

Fix Nric parser

---

docs/DeveloperGuide.adoc
docs/UserGuide.adoc

Add updates to guides

---

docs/UserGuide.adoc

Refer to issues #179 #180 #181 #188 #189 #192 #194 #196 #199 #200 #207 #213 #214

Fix grammar and nits UG

---

src/main/java/loanbook/logic/commands/DeleteBikeCommand.java
src/main/java/loanbook/logic/commands/FindCommand.java
src/main/java/loanbook/logic/parser/DeleteBikeCommandParser.java
src/main/java/loanbook/logic/parser/LoanBookParser.java
src/main/java/loanbook/model/ModelManager.java
src/main/java/loanbook/model/loan/NameContainsKeywordsPredicate.java
src/test/java/loanbook/logic/commands/CommandTestUtil.java
src/test/java/loanbook/logic/commands/DeleteBikeCommandTest.java
src/test/java/loanbook/logic/commands/FindCommandTest.java
src/test/java/loanbook/logic/parser/DeleteBikeCommandParserTest.java
src/test/java/loanbook/model/ModelManagerTest.java
src/test/java/loanbook/model/loan/NameContainsKeywordsPredicateTest.java

For https://github.com/CS2103-AY1819S1-F10-2/main/issues/48

add deletebike command

---

src/main/java/loanbook/logic/commands/EditBikeCommand.java
src/main/java/loanbook/logic/parser/EditBikeCommandParser.java
src/main/java/loanbook/logic/parser/LoanBookParser.java
src/test/java/loanbook/logic/commands/CommandTestUtil.java
src/test/java/loanbook/logic/commands/EditBikeCommandTest.java
src/test/java/loanbook/logic/commands/EditBikeDescriptorTest.java
src/test/java/loanbook/logic/parser/EditBikeCommandParserTest.java
src/test/java/loanbook/testutil/EditBikeDescriptorBuilder.java

For https://github.com/CS2103-AY1819S1-F10-2/main/issues/47

Add editbike command

---

docs/UserGuide.adoc

Fix #186 #187 #191 #198 #216 #217 #219 #232 #236

Fix issues in UG examples

---

src/test/java/loanbook/commons/core/index/IndexTest.java
src/test/java/loanbook/logic/CommandHistoryTest.java
src/test/java/loanbook/logic/ListElementPointerTest.java
src/test/java/loanbook/logic/commands/AddCommandTest.java
src/test/java/loanbook/logic/commands/DeleteBikeCommandTest.java
src/test/java/loanbook/logic/commands/DeleteCommandTest.java
src/test/java/loanbook/logic/commands/EditBikeCommandTest.java
src/test/java/loanbook/logic/commands/EditBikeDescriptorTest.java
src/test/java/loanbook/logic/commands/EditCommandTest.java
src/test/java/loanbook/logic/commands/EditLoanDescriptorTest.java
src/test/java/loanbook/logic/commands/FindCommandTest.java
src/test/java/loanbook/logic/commands/RemindCommandTest.java
src/test/java/loanbook/logic/commands/ReturnCommandTest.java
src/test/java/loanbook/logic/commands/SearchCommandTest.java
src/test/java/loanbook/logic/commands/SelectCommandTest.java
src/test/java/loanbook/logic/commands/SetEmailCommandTest.java
src/test/java/loanbook/logic/commands/SetPasswordCommandTest.java
src/test/java/loanbook/model/ModelManagerTest.java
src/test/java/loanbook/model/VersionedLoanBookTest.java
src/test/java/loanbook/model/loan/LoanTest.java
src/test/java/loanbook/model/loan/NameContainsKeywordsPredicateTest.java

Changes `xxx.equals(null)` statements to `xxx == null`.

Fix equals(null) tests

---

docs/UserGuide.adoc

fix UG errors

---

src/main/java/loanbook/logic/commands/Summary.java
src/main/java/loanbook/logic/commands/SummaryCommand.java
src/main/java/loanbook/logic/parser/LoanBookParser.java
src/test/java/loanbook/logic/commands/SummaryCommandTest.java

Fix issue #221 
Enhancement tracker #107 can then be updated.

Add summary functionality

---

src/main/java/loanbook/logic/parser/CliSyntax.java
src/main/java/loanbook/logic/parser/ParserUtil.java
src/main/java/loanbook/model/LoanBook.java
src/main/java/loanbook/model/Model.java
src/main/java/loanbook/model/ModelManager.java
src/main/java/loanbook/model/loan/UniqueLoanList.java
src/test/java/loanbook/logic/parser/ParserUtilTest.java
src/test/java/loanbook/model/ModelManagerTest.java
src/test/java/loanbook/testutil/ModelStub.java

Add getLoanById method and LoanID parser

---

docs/UserGuide.adoc
src/main/java/loanbook/commons/core/Messages.java
src/main/java/loanbook/model/loan/Nric.java

Fixes the following issues:
Fix #208 
Fix #201 
Documentation to fix following issue by v2.0
- Fix #225 
- Fix #202 
- Fix #108 
- Fix #173

Fix issue from dry run

---

docs/team/kelly9373.adoc

Fix Xiaohang PPP
